apiVersion: v1
appVersion: lts
name: jenkins
master:
  component.Name: "jenkins-master"
  image: "jenkins/jenkins"
  imagePullPolicy: "IfNotPresent"
  imageTag: "2.181-alpine"
  Cpu: "300m"
  Memory: "900Mi"
  serviceType: ClusterIP
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  installPlugins:
  - ant:1.9
  - durable-task:1.29
  - workflow-durable-task-step:2.31
  - blueocean:1.17.0
  - credentials:2.2.0
  - ec2:1.43
  - git:3.10.0
  - git-client:2.8.0
  - github:1.29.4
  - kubernetes:1.14.3
  - pipeline-utility-steps:2.3.0
  - pipeline-model-definition:1.3.9
  - slack:2.23
  - thinBackup:1.9
  - workflow-aggregator:2.6
  - ssh-slaves:1.30.0
  - ssh-agent:1.17
  - jdk-tool:1.2
  - command-launcher:1.3
  - github-oauth:0.32
  - pegdown-formatter:1.3
  - pipeline-aws:1.38
  - matrix-auth:2.4.2
  - pam-auth:1.5.1
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: 50m
      ingress.kubernetes.io/proxy-request-buffering: "off"
  HostName: jenkins.dev.easynvest.io
agent:
  enabled: true
  image: renizgo/jnlp-slave
  imageTag: latest
  CustomJenkinsLabels: []
# ImagePullSecret: jenkins
  imagePullPolicy: Always
  Component: "jenkins-slave"
  Privileged: true
  resources:
    requests:
      cpu: "500m"
      memory: "756Mi"
    limits:
      cpu: "500m"
      memory: "756Mi"
rbac:
  create: true
#  roleBindingKind: RoleBinding
persistence:
  Enabled: true
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 20Gi
  volumes:
    - name: backup
      emptyDir: {}
  mounts:
   - mountPath: /backup
     name: backup
